/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
    
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
 
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
#include <stdio.h>


int main()
{
    int max_fib = 4000000;

    int a = 1;
    int b = 2;
    int temp = 0;
    int sum = 0;

    while (b < max_fib)
    {
        if (b % 2 == 0)
            sum += b;

        temp = a + b;
        a = b;
        b = temp;
    }

    printf("solution: %d\n", sum);
    
    return 0;
}
