/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55...
Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6:  1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <stdint.h>

uint32_t divisorCount(uint64_t N)
{
    uint32_t divCount = 1;
    uint32_t expCount = 1; 
    uint32_t div = 2;
    while (N > 1)
    {
        expCount = 1;
        while (N % div == 0)
        {
            N /= div;
            expCount++;
        }
        divCount *= expCount;
        div++;
    }
    return divCount;
}

int main()
{
    uint32_t n = 1;
    uint32_t divCount = 1;
    uint64_t triangleNumber = 0;
 
    while (divCount < 500)
    {
        triangleNumber = (n*(n + 1)) / 2;
        divCount = divisorCount(triangleNumber);
        n++;
    }
   
    printf("The %uth Triangle Number %lu has %u divisors\n", n, triangleNumber, divCount);

    return 0;
}




